<?php

use Illuminate\Database\Seeder;

/**
* Die ArtikelTableSeeder-Klasse füllt die Artikel-Tabelle mit den angegebenen Werten
*/
class ArtikelTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('Artikel')->delete();
      DB::table('Artikel')->insert([
          [
            'Artikel_Produkte_ID' => '1',
            'Seriennummer' => 'TRINC-GRID-21321312313',
            'EKP_Artikel' => '10000',
            'EKP_Artikel_Waehrungen_ID' => '1',
            'VKP_Artikel' => '15000',
            'VKP_Artikel_Waehrungen_ID' => '1',
            'Auftragsnummer' => 'AT-23423423424',
            'Auftragsdatum' => '2012-04-05',
            'Rechnungsnummer' => 'RE-23423424324',
            'Rechnungsdatum' => '2012-06-20',
            'Artikel_Maintenance_ID' => '1',
            'Maintenance_Start' => '2013-01-01',
            'Maintenance_von' => '2013-01-20',
            'Maintenance_bis' => '2013-11-20',
            'EKP_Maintenance' => '1000',
            'EKP_Maintenance_Waehrungen_ID' => '1',
            'VKP_Maintenance' => '1300',
            'VKP_Maintenance_Waehrungen_ID' => '1',
            'Artikel_Operationsupport_ID' => '1',
            'Operationsupport_Start' => '2013-01-01',
            'Operationsupport_von' => '2013-01-01',
            'Operationsupport_bis' => '2015-12-31',
            'VKP_Operationsupport' => '1',
            'VKP_Operationsupport_Waehrungen_ID' => '1',
            'Artikel_Wartungsvertraege_ID' => '1',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
          ],
          [
            'Artikel_Produkte_ID' => '4',
            'Seriennummer' => 'IB-Grid22',
            'EKP_Artikel' => '230000',
            'EKP_Artikel_Waehrungen_ID' => '1',
            'VKP_Artikel' => '300000',
            'VKP_Artikel_Waehrungen_ID' => '1',
            'Auftragsnummer' => 'AT-234234234243',
            'Auftragsdatum' => '2012-04-05',
            'Rechnungsnummer' => 'RE-234234243242',
            'Rechnungsdatum' => '2012-06-20',
            'Artikel_Maintenance_ID' => '3',
            'Maintenance_Start' => '2013-01-01',
            'Maintenance_von' => '2013-01-20',
            'Maintenance_bis' => '2013-11-20',
            'EKP_Maintenance' => '1300',
            'EKP_Maintenance_Waehrungen_ID' => '1',
            'VKP_Maintenance' => '1700',
            'VKP_Maintenance_Waehrungen_ID' => '1',
            'Artikel_Operationsupport_ID' => '3',
            'Operationsupport_Start' => '2013-01-01',
            'Operationsupport_von' => '2013-01-01',
            'Operationsupport_bis' => '2015-12-31',
            'VKP_Operationsupport' => '1',
            'VKP_Operationsupport_Waehrungen_ID' => '1',
            'Artikel_Wartungsvertraege_ID' => '2',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
          ],
          [
            'Artikel_Produkte_ID' => '6',
            'Seriennummer' => 'AUDIT-P-23235435ac',
            'EKP_Artikel' => '20000',
            'EKP_Artikel_Waehrungen_ID' => '1',
            'VKP_Artikel' => '27000',
            'VKP_Artikel_Waehrungen_ID' => '1',
            'Auftragsnummer' => 'AT-23423423424-34',
            'Auftragsdatum' => '2012-04-05',
            'Rechnungsnummer' => 'RE-23423424324-23',
            'Rechnungsdatum' => '2012-06-20',
            'Artikel_Maintenance_ID' => '5',
            'Maintenance_Start' => '2013-01-01',
            'Maintenance_von' => '2013-01-20',
            'Maintenance_bis' => '2013-11-20',
            'EKP_Maintenance' => '1300',
            'EKP_Maintenance_Waehrungen_ID' => '1',
            'VKP_Maintenance' => '1700',
            'VKP_Maintenance_Waehrungen_ID' => '1',
            'Artikel_Operationsupport_ID' => '5',
            'Operationsupport_Start' => '2013-01-01',
            'Operationsupport_von' => '2013-01-01',
            'Operationsupport_bis' => '2015-12-31',
            'VKP_Operationsupport' => '1',
            'VKP_Operationsupport_Waehrungen_ID' => '1',
            'Artikel_Wartungsvertraege_ID' => '2',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
          ],
          [
            'Artikel_Produkte_ID' => '3',
            'Seriennummer' => 'TRIN-1420-234234',
            'EKP_Artikel' => '10000',
            'EKP_Artikel_Waehrungen_ID' => '2',
            'VKP_Artikel' => '12000',
            'VKP_Artikel_Waehrungen_ID' => '1',
            'Auftragsnummer' => 'AT-234234234243',
            'Auftragsdatum' => '2012-04-05',
            'Rechnungsnummer' => 'RE-234234243242',
            'Rechnungsdatum' => '2012-06-20',
            'Artikel_Maintenance_ID' => '3',
            'Maintenance_Start' => '2013-01-01',
            'Maintenance_von' => '2013-01-20',
            'Maintenance_bis' => '2013-11-20',
            'EKP_Maintenance' => '1300',
            'EKP_Maintenance_Waehrungen_ID' => '1',
            'VKP_Maintenance' => '1700',
            'VKP_Maintenance_Waehrungen_ID' => '1',
            'Artikel_Operationsupport_ID' => '3',
            'Operationsupport_Start' => '2013-01-01',
            'Operationsupport_von' => '2013-01-01',
            'Operationsupport_bis' => '2015-12-31',
            'VKP_Operationsupport' => '1',
            'VKP_Operationsupport_Waehrungen_ID' => '1',
            'Artikel_Wartungsvertraege_ID' => '2',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
          ],
          [
            'Artikel_Produkte_ID' => '3',
            'Seriennummer' => 'TRIN-1420-234235',
            'EKP_Artikel' => '10000',
            'EKP_Artikel_Waehrungen_ID' => '2',
            'VKP_Artikel' => '12000',
            'VKP_Artikel_Waehrungen_ID' => '1',
            'Auftragsnummer' => 'AT-234234234243',
            'Auftragsdatum' => '2012-04-05',
            'Rechnungsnummer' => 'RE-234234243242',
            'Rechnungsdatum' => '2012-06-20',
            'Artikel_Maintenance_ID' => '5',
            'Maintenance_Start' => '2013-01-01',
            'Maintenance_von' => '2013-01-20',
            'Maintenance_bis' => '2013-11-20',
            'EKP_Maintenance' => '1300',
            'EKP_Maintenance_Waehrungen_ID' => '1',
            'VKP_Maintenance' => '1700',
            'VKP_Maintenance_Waehrungen_ID' => '1',
            'Artikel_Operationsupport_ID' => '5',
            'Operationsupport_Start' => '2013-01-01',
            'Operationsupport_von' => '2013-01-01',
            'Operationsupport_bis' => '2015-12-31',
            'VKP_Operationsupport' => '1',
            'VKP_Operationsupport_Waehrungen_ID' => '1',
            'Artikel_Wartungsvertraege_ID' => '2',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
          ],
          [
            'Artikel_Produkte_ID' => '5',
            'Seriennummer' => 'DYNTR234234',
            'EKP_Artikel' => '20000',
            'EKP_Artikel_Waehrungen_ID' => '2',
            'VKP_Artikel' => '21030',
            'VKP_Artikel_Waehrungen_ID' => '1',
            'Auftragsnummer' => 'AT-23434342',
            'Auftragsdatum' => '2012-04-05',
            'Rechnungsnummer' => 'RE-23423422',
            'Rechnungsdatum' => '2012-06-20',
            'Artikel_Maintenance_ID' => '1',
            'Maintenance_Start' => '2013-01-01',
            'Maintenance_von' => '2013-01-20',
            'Maintenance_bis' => '2013-11-20',
            'EKP_Maintenance' => '1300',
            'EKP_Maintenance_Waehrungen_ID' => '1',
            'VKP_Maintenance' => '1700',
            'VKP_Maintenance_Waehrungen_ID' => '1',
            'Artikel_Operationsupport_ID' => '1',
            'Operationsupport_Start' => '2013-01-01',
            'Operationsupport_von' => '2013-01-01',
            'Operationsupport_bis' => '2014-12-31',
            'VKP_Operationsupport' => '1',
            'VKP_Operationsupport_Waehrungen_ID' => '1',
            'Artikel_Wartungsvertraege_ID' => '4',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
          ],
          [
            'Artikel_Produkte_ID' => '1',
            'Seriennummer' => 'TE-810-2342342',
            'EKP_Artikel' => '5000',
            'EKP_Artikel_Waehrungen_ID' => '1',
            'VKP_Artikel' => '6030',
            'VKP_Artikel_Waehrungen_ID' => '1',
            'Auftragsnummer' => 'AT-23434342',
            'Auftragsdatum' => '2012-04-05',
            'Rechnungsnummer' => 'RE-23423422',
            'Rechnungsdatum' => '2012-06-20',
            'Artikel_Maintenance_ID' => '3',
            'Maintenance_Start' => '2013-01-01',
            'Maintenance_von' => '2013-01-20',
            'Maintenance_bis' => '2015-11-20',
            'EKP_Maintenance' => '1300',
            'EKP_Maintenance_Waehrungen_ID' => '1',
            'VKP_Maintenance' => '1700',
            'VKP_Maintenance_Waehrungen_ID' => '1',
            'Artikel_Operationsupport_ID' => '3',
            'Operationsupport_Start' => '2013-01-01',
            'Operationsupport_von' => '2013-01-01',
            'Operationsupport_bis' => '2015-12-31',
            'VKP_Operationsupport' => '1',
            'VKP_Operationsupport_Waehrungen_ID' => '1',
            'Artikel_Wartungsvertraege_ID' => '4',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
          ]
      ]);
    }
}
